name: Build and deploy Zola website
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      - name: Build Zola
        uses: ./.github/actions/build-zola
        with:
          zola_version: v0.21.0
          check_links: true
          check_flags: --skip-external-links

      - name: Minifying JS and CSS
        run: |
          sudo apt-get install minify
          sudo minify -r . -o .
        working-directory: ./public

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
